### ISSUE TITLE
Коммент от кота

### ISSUE THREAD

**Issue by nomoregeek** [prolidorpenrvapiroldon/RPGame#1]
Ну чего как? Чего такое пишешь?

**Comment by prolidorpenrvapiroldon** [comment]
Решил повторить ООП, попрыгал по темам, и понял что у меня нету цельной картины об этом. Вот решил написать игру. Также хочу попробовать встроить паттерны, я раньше ими вообще не пользовался. Поработаю в целом над ошибками с проектированием.

Особой картины игры у меня нету, что придет в голову, то и добавлю..
